---
  - name: Print IP Address
    shell:  "dig +short myip.opendns.com @resolver1.opendns.com."
    register: print_result

  #show the output on the user/us Cli
  - name: print message
    debug:
      msg: "{{ print_result.stdout_lines }}"

  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes



  - name: "Copy YAML Files"
    become: yes
    become_user: bitnami
    copy:
      src: nginx-deployment.yaml
      dest: /home/bitnami/
    
  - name: "Copy YAML Files 2"
    become: yes
    become_user: bitnami
    copy:
      src: nginx-service.yaml
      dest: /home/bitnami/
      owner: bitnami

  - name: "Deploy - creating log files and directories"
    become: yes
    become_user: root
    shell: |
      echo "hi"
      cd /home/bitnami
      sudo touch file.txt