---
  - name: Print IP Address
    shell:  "dig +short myip.opendns.com @resolver1.opendns.com."
    register: print_result

  #show the output on the user/us Cli
  - name: print message
    debug:
      msg: "{{ print_result.stdout_lines }}"





  - name: "Copy YAML Files"
    become: yes
    become_user: bitnami
    copy:
      src: nginx-deployment.yaml
      dest: /home/bitnami/
    
  - name: "Copy YAML Files 2"
    become: yes
    become_user: bitnami
    copy:
      src: nginx-service.yaml
      dest: /home/bitnami/
      owner: bitnami

  - name: "Deploy Kubernetes Cluster"
    become: yes
    become_user: root
    shell: |
      cd /home/bitnami
      sudo kubectl create ns nginx
      sudo kubectl create -f nginx-deployment.yaml
      sudo kubectl create -f nginx-service.yaml
      sudo kubectl get deployment -n nginx
      sudo kubectl get pods -n nginx
      sudo kubectl get svc -n nginx