apiVersion: v1
kind: Service
metadata:
  name: mywebsite-svc
  namespace: mywebsite
  labels:
    app: mywebsite
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31234
  selector:
    app: mywebsite